import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// @ts-expect-error — the distribute script is plain ESM (.mjs) with no .d.ts.
import {
  applyBanner,
  distribute,
  loadConfig,
  loadReceipt,
  parseArgs,
  receiptPathFor,
  renderDaemonLauncher,
} from "../../../scripts/distribute.mjs";

/**
 * These tests exercise the distribute.mjs helpers hermetically: a FAKE repo
 * root with stub bundle/doc source files and temp target dirs. Every call
 * passes `build: false`, so pnpm is NEVER spawned (fast, no real build).
 */

let workDir: string;
let fakeRepoRoot: string;

/** Lay down the four source artifacts the distributor expects under a fake root. */
function seedSources(root: string): void {
  mkdirSync(join(root, "packages", "mcp-server", "dist", "bundle"), { recursive: true });
  mkdirSync(join(root, "packages", "integrator-ref", "dist", "bundle"), {
    recursive: true,
  });
  mkdirSync(join(root, "docs"), { recursive: true });
  writeFileSync(
    join(root, "packages", "mcp-server", "dist", "bundle", "pm-mcp-server.mjs"),
    "MCP_BUNDLE_CONTENT",
  );
  writeFileSync(
    join(root, "packages", "integrator-ref", "dist", "bundle", "pm-integrator.mjs"),
    "INTEGRATOR_BUNDLE_CONTENT",
  );
  writeFileSync(join(root, "docs", "integrator-deployment.md"), "OPERATOR_GUIDE");
  writeFileSync(join(root, "docs", "worker-pm-workflow.md"), "WORKER_WORKFLOW");
}

beforeEach(() => {
  workDir = mkdtempSync(join(tmpdir(), "distribute-test-"));
  fakeRepoRoot = join(workDir, "repo");
  mkdirSync(fakeRepoRoot, { recursive: true });
});

afterEach(() => {
  rmSync(workDir, { recursive: true, force: true });
});

describe("distribute (build: false)", () => {
  it("copies all 4 artifacts to a target, creating nested dest dirs", () => {
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "deep", "nested", "target");
    const config = {
      targets: [
        {
          name: "t1",
          mcpDest: join(targetDir, "tools", "pm-mcp-server", "pm-mcp-server.mjs"),
          integratorDest: join(targetDir, "tools", "pm-integrator", "pm-integrator.mjs"),
          docsDest: join(targetDir, "docs", "integrator-deployment.md"),
          // Worker doc must land AS pm-workflow.md (the rename) per the dest path.
          workerDocDest: join(targetDir, "docs", "pm-workflow.md"),
        },
      ],
    };

    distribute({ config, repoRoot: fakeRepoRoot, build: false });

    // Each destination now carries a generated-file banner ahead of the payload:
    // a reader who opens the file is told, in the file, that editing it is futile.
    const t = config.targets[0];
    const mcp = readFileSync(t.mcpDest, "utf8");
    const integrator = readFileSync(t.integratorDest, "utf8");
    const guide = readFileSync(t.docsDest, "utf8");
    const worker = readFileSync(t.workerDocDest, "utf8");

    expect(mcp).toContain("MCP_BUNDLE_CONTENT");
    expect(integrator).toContain("INTEGRATOR_BUNDLE_CONTENT");
    expect(guide).toContain("OPERATOR_GUIDE");
    expect(worker).toContain("WORKER_WORKFLOW");

    // .mjs gets a `//` banner, .md an HTML comment that renders invisibly.
    expect(mcp.split("\n")[0]).toMatch(/^\/\/ GENERATED by scripts\/distribute\.mjs/);
    expect(integrator.split("\n")[0]).toMatch(/^\/\/ GENERATED by scripts\/distribute\.mjs/);
    expect(guide.split("\n")[0]).toMatch(/^<!-- GENERATED by scripts\/distribute\.mjs/);
    expect(worker.split("\n")[0]).toMatch(/^<!-- GENERATED by scripts\/distribute\.mjs/);
    // The banner names the SOURCE, so the reader knows where to make the edit.
    expect(worker).toContain("docs/worker-pm-workflow.md");
  });

  it("throws clearly naming the missing bundle path, with no partial copy", () => {
    seedSources(fakeRepoRoot);
    // Remove the MCP bundle to simulate a skipped build.
    rmSync(join(fakeRepoRoot, "packages", "mcp-server", "dist", "bundle", "pm-mcp-server.mjs"));

    const targetDir = join(workDir, "target");
    const config = {
      targets: [
        {
          name: "t1",
          mcpDest: join(targetDir, "pm-mcp-server.mjs"),
          integratorDest: join(targetDir, "pm-integrator.mjs"),
          docsDest: join(targetDir, "integrator-deployment.md"),
          workerDocDest: join(targetDir, "pm-workflow.md"),
        },
      ],
    };

    expect(() => distribute({ config, repoRoot: fakeRepoRoot, build: false })).toThrow(
      /pm-mcp-server\.mjs/,
    );
    // Source assertion happens before any copy — nothing should have landed.
    expect(existsSync(config.targets[0].docsDest)).toBe(false);
  });

  it("dryRun writes zero files", () => {
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "target");
    const config = {
      targets: [
        {
          name: "t1",
          mcpDest: join(targetDir, "pm-mcp-server.mjs"),
          integratorDest: join(targetDir, "pm-integrator.mjs"),
          docsDest: join(targetDir, "integrator-deployment.md"),
          workerDocDest: join(targetDir, "pm-workflow.md"),
        },
      ],
    };

    distribute({ config, repoRoot: fakeRepoRoot, build: false, dryRun: true });

    expect(existsSync(targetDir)).toBe(false);
    for (const dest of Object.values(config.targets[0])) {
      if (typeof dest === "string" && dest.includes(workDir)) {
        expect(existsSync(dest)).toBe(false);
      }
    }
  });
});

describe("renderDaemonLauncher", () => {
  const opts = {
    bundleName: "pm-integrator.mjs",
    projectId: "01PROJECT",
    resource: "main",
    pmUrl: "http://localhost:3000",
  };

  it("renders a .bat that invokes the supervised .ps1 (no dev-repo path) with CRLF", () => {
    const bat = renderDaemonLauncher("bat", opts);
    // The .bat is a thin invoker; supervision lives in run_daemon_supervised.ps1.
    expect(bat).toContain(
      'powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0run_daemon_supervised.ps1" %*',
    );
    expect(bat).not.toMatch(/project-management|integrator-ref|dist[\\/]index/);
    expect(bat).toContain("\r\n");
  });

  it("renders a supervised .ps1 that runs the local bundle, with a single-instance mutex, CRLF", () => {
    const ps1 = renderDaemonLauncher("ps1", opts);
    // Launches the bundle with the templated daemon args.
    expect(ps1).toContain(
      "$psi.Arguments = '\"' + $bundle + '\" --project 01PROJECT --resource main --pm-url http://localhost:3000'",
    );
    expect(ps1).toContain("$BundleName = 'pm-integrator.mjs'");
    // Single-instance guard + token load from the gitignored sibling, never the monorepo.
    expect(ps1).toContain('New-Object System.Threading.Mutex($false, "Global\\pm-integrator-');
    expect(ps1).toContain("$env:PM_API_TOKEN = (Get-Content -Raw $tokenFile).Trim()");
    expect(ps1).not.toMatch(/project-management|integrator-ref|dist[\\/]index/);
    expect(ps1).toContain("\r\n");
  });

  it("renders a supervised .sh (flock single-instance, restart loop) with LF line endings", () => {
    const sh = renderDaemonLauncher("sh", opts);
    expect(sh).toContain(
      'node "$BUNDLE" --project 01PROJECT --resource main --pm-url http://localhost:3000 "$@" &',
    );
    expect(sh).toContain('export PM_API_TOKEN="$(cat "$DIR/pm_token.txt")"');
    expect(sh).toContain("flock -n 9"); // single-instance guard
    expect(sh).toContain("while true; do"); // supervised restart loop
    expect(sh).not.toContain("\r\n");
  });

  it("references the bundle by its actual basename (in the .ps1 and .sh)", () => {
    const ps1 = renderDaemonLauncher("ps1", { ...opts, bundleName: "custom-daemon.mjs" });
    expect(ps1).toContain("$BundleName = 'custom-daemon.mjs'");
    const sh = renderDaemonLauncher("sh", { ...opts, bundleName: "custom-daemon.mjs" });
    expect(sh).toContain('BUNDLE="$DIR/custom-daemon.mjs"');
  });

  it("defaults resource to main and pmUrl to localhost:3000 when omitted", () => {
    const ps1 = renderDaemonLauncher("ps1", {
      bundleName: "pm-integrator.mjs",
      projectId: "01PROJECT",
    });
    expect(ps1).toContain("--resource main --pm-url http://localhost:3000");
  });

  it("throws on an unknown kind", () => {
    expect(() => renderDaemonLauncher("exe", opts)).toThrow(/Unknown launcher kind/);
  });
});

describe("distribute — daemon launcher emission", () => {
  function launcherConfig(targetDir: string, extra: Record<string, unknown> = {}) {
    return {
      targets: [
        {
          name: "t1",
          mcpDest: join(targetDir, "tools", "pm-mcp-server", "pm-mcp-server.mjs"),
          integratorDest: join(targetDir, "tools", "pm-integrator", "pm-integrator.mjs"),
          docsDest: join(targetDir, "docs", "integrator-deployment.md"),
          workerDocDest: join(targetDir, "docs", "pm-workflow.md"),
          ...extra,
        },
      ],
    };
  }

  it("emits run_daemon.bat + run_daemon_supervised.ps1 + .sh + pm_token.txt.template next to the bundle when projectId is set", () => {
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "target");
    const config = launcherConfig(targetDir, {
      projectId: "01KSMSZVN87QWZZBY7AR7QV149",
      resource: "main",
      pmUrl: "http://localhost:3000",
    });

    distribute({ config, repoRoot: fakeRepoRoot, build: false });

    const launcherDir = join(targetDir, "tools", "pm-integrator");
    const bat = readFileSync(join(launcherDir, "run_daemon.bat"), "utf8");
    expect(bat).toContain("run_daemon_supervised.ps1");
    // The supervised .ps1 carries the daemon args.
    const ps1 = readFileSync(join(launcherDir, "run_daemon_supervised.ps1"), "utf8");
    expect(ps1).toContain("--project 01KSMSZVN87QWZZBY7AR7QV149 --resource main");
    expect(existsSync(join(launcherDir, "run_daemon.sh"))).toBe(true);
    expect(readFileSync(join(launcherDir, "pm_token.txt.template"), "utf8")).toContain(
      "paste-your-pm-api-token-here",
    );
    // Never writes the real secret file.
    expect(existsSync(join(launcherDir, "pm_token.txt"))).toBe(false);
  });

  it("emits NO launcher when projectId is absent (back-compat)", () => {
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "target");
    const config = launcherConfig(targetDir);

    distribute({ config, repoRoot: fakeRepoRoot, build: false });

    const launcherDir = join(targetDir, "tools", "pm-integrator");
    expect(existsSync(join(launcherDir, "run_daemon.bat"))).toBe(false);
    expect(existsSync(join(launcherDir, "run_daemon.sh"))).toBe(false);
    // The bundle itself still landed.
    expect(existsSync(join(launcherDir, "pm-integrator.mjs"))).toBe(true);
  });

  it("dryRun writes no launcher files even with projectId set", () => {
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "target");
    const config = launcherConfig(targetDir, { projectId: "01PROJECT" });

    distribute({ config, repoRoot: fakeRepoRoot, build: false, dryRun: true });

    expect(existsSync(join(targetDir, "tools", "pm-integrator", "run_daemon.bat"))).toBe(false);
  });

  it("loadConfig rejects a non-empty-string projectId", () => {
    const bad = join(workDir, "badpid.json");
    writeFileSync(
      bad,
      JSON.stringify({
        targets: [
          {
            name: "t1",
            mcpDest: "/a",
            integratorDest: "/b",
            docsDest: "/c",
            workerDocDest: "/d",
            projectId: "",
          },
        ],
      }),
    );
    expect(() => loadConfig(bad)).toThrow(/projectId/);
  });
});

describe("loadConfig", () => {
  it("throws a clear error when the config path is missing", () => {
    const missing = join(workDir, "nope.json");
    expect(() => loadConfig(missing)).toThrow(/not found/);
    expect(() => loadConfig(missing)).toThrow(/distribute\.config\.example\.json/);
  });

  it("throws a distinct error on malformed JSON", () => {
    const bad = join(workDir, "bad.json");
    writeFileSync(bad, "{ not valid json ");
    expect(() => loadConfig(bad)).toThrow(/not valid JSON/);
  });

  it("rejects an empty targets array", () => {
    const empty = join(workDir, "empty.json");
    writeFileSync(empty, JSON.stringify({ targets: [] }));
    expect(() => loadConfig(empty)).toThrow(/non-empty "targets"/);
  });

  it("rejects a target missing a required field", () => {
    const partial = join(workDir, "partial.json");
    writeFileSync(
      partial,
      JSON.stringify({
        targets: [{ name: "t1", mcpDest: "/a", integratorDest: "/b", docsDest: "/c" }],
      }),
    );
    expect(() => loadConfig(partial)).toThrow(/workerDocDest/);
  });

  it("accepts a well-formed config", () => {
    const ok = join(workDir, "ok.json");
    const config = {
      targets: [
        {
          name: "t1",
          mcpDest: "/a",
          integratorDest: "/b",
          docsDest: "/c",
          workerDocDest: "/d",
        },
      ],
    };
    writeFileSync(ok, JSON.stringify(config));
    expect(loadConfig(ok).targets).toHaveLength(1);
  });
});

describe("parseArgs", () => {
  it("defaults config to repoRoot/distribute.config.json and dryRun false", () => {
    const args = parseArgs([]);
    expect(args.dryRun).toBe(false);
    expect(args.config).toMatch(/distribute\.config\.json$/);
  });

  it("parses --config <path> and --dry-run", () => {
    const args = parseArgs(["--config", "/custom/cfg.json", "--dry-run"]);
    expect(args.config).toBe("/custom/cfg.json");
    expect(args.dryRun).toBe(true);
  });

  it("parses --config=<path> form", () => {
    const args = parseArgs(["--config=/inline/cfg.json"]);
    expect(args.config).toBe("/inline/cfg.json");
  });

  it("throws on --config with no value", () => {
    expect(() => parseArgs(["--config"])).toThrow(/requires a path/);
  });

  it("throws on an unknown argument", () => {
    expect(() => parseArgs(["--wat"])).toThrow(/Unknown argument/);
  });
});

/**
 * Write receipts: distribute must not silently overwrite a destination that
 * changed since it last wrote it.
 *
 * The case these defend is real. On 2026-09-19 game_one's docs/pm-workflow.md
 * held 33 lines added downstream by d412a393f that do not exist upstream; a
 * distribute would have removed exactly those 33 lines and re-added the 3 they
 * replaced, reporting nothing. It was caught by a human reading a 36-line diff
 * inside a change about a bundle -- which is luck, not a control.
 */
describe("distribute write receipts", () => {
  function cfg(targetDir: string) {
    return {
      targets: [
        {
          name: "t1",
          mcpDest: join(targetDir, "pm-mcp-server.mjs"),
          integratorDest: join(targetDir, "pm-integrator.mjs"),
          docsDest: join(targetDir, "integrator-deployment.md"),
          workerDocDest: join(targetDir, "pm-workflow.md"),
        },
      ],
    };
  }

  it("records a receipt beside the config, keyed by destination", () => {
    seedSources(fakeRepoRoot);
    const config = cfg(join(workDir, "target"));
    const receiptPath = join(workDir, "distribute.receipt.json");

    distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath });

    expect(existsSync(receiptPath)).toBe(true);
    const writes = loadReceipt(receiptPath);
    for (const dest of [
      config.targets[0].mcpDest,
      config.targets[0].integratorDest,
      config.targets[0].docsDest,
      config.targets[0].workerDocDest,
    ]) {
      expect(writes[dest]).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  it("a second run over its own untouched output succeeds", () => {
    seedSources(fakeRepoRoot);
    const config = cfg(join(workDir, "target"));
    const receiptPath = join(workDir, "distribute.receipt.json");

    distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath });
    expect(() =>
      distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath }),
    ).not.toThrow();
  });

  it("REFUSES a destination edited since the last write, naming it, and writes nothing", () => {
    seedSources(fakeRepoRoot);
    const config = cfg(join(workDir, "target"));
    const receiptPath = join(workDir, "distribute.receipt.json");
    distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath });

    // Someone edits the destination downstream -- the pm-workflow.md case.
    writeFileSync(config.targets[0].workerDocDest, "WORKER_WORKFLOW plus a local paragraph");
    // ...and the upstream source moves on, so a naive run would overwrite it.
    writeFileSync(join(fakeRepoRoot, "docs", "worker-pm-workflow.md"), "WORKER_WORKFLOW v2");

    expect(() => distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath })).toThrow(
      /changed since distribute last wrote it/,
    );

    // The edit survives, and so does every other destination: the refusal happens
    // before ANY file is written, so the run cannot land half of itself.
    expect(readFileSync(config.targets[0].workerDocDest, "utf8")).toContain("a local paragraph");
    expect(readFileSync(config.targets[0].docsDest, "utf8")).toContain("OPERATOR_GUIDE");
  });

  it("--force overwrites a diverged destination, discarding the downstream edit", () => {
    seedSources(fakeRepoRoot);
    const config = cfg(join(workDir, "target"));
    const receiptPath = join(workDir, "distribute.receipt.json");
    distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath });
    writeFileSync(config.targets[0].workerDocDest, "WORKER_WORKFLOW plus a local paragraph");

    distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath, force: true });

    const after = readFileSync(config.targets[0].workerDocDest, "utf8");
    expect(after).toContain("WORKER_WORKFLOW");
    expect(after).not.toContain("a local paragraph");
  });

  it("REFUSES an unrecorded destination that differs -- the bootstrap is not permissive", () => {
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "target");
    const config = cfg(targetDir);
    const receiptPath = join(workDir, "distribute.receipt.json");

    // A destination that predates receipts and holds content of its own. Without
    // a record, a hand-edit and a stale copy are indistinguishable -- so refuse.
    mkdirSync(targetDir, { recursive: true });
    writeFileSync(config.targets[0].workerDocDest, "SOMETHING NOBODY RECORDED");

    expect(() => distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath })).toThrow(
      /no record of distribute having written it/,
    );
    expect(readFileSync(config.targets[0].workerDocDest, "utf8")).toBe("SOMETHING NOBODY RECORDED");
  });

  it("the first-run refusal EXPLAINS ITSELF: expected, what to do, and not --force", () => {
    // An operator meets this error mid-deployment, in a hurry, once. If it reads as
    // a fault they will reach for the flag that makes it go away -- which is --force,
    // the one outcome the refusal exists to prevent. So the text has to say: this is
    // expected, here is the procedure, and not that flag.
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "target");
    const config = cfg(targetDir);
    const receiptPath = join(workDir, "distribute.receipt.json");
    mkdirSync(targetDir, { recursive: true });
    writeFileSync(config.targets[0].workerDocDest, "SOMETHING NOBODY RECORDED");

    let message = "";
    try {
      distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath });
    } catch (err) {
      message = (err as Error).message;
    }

    expect(message).toContain("EXPECTED ON THE FIRST RUN");
    expect(message).toContain("refuses exactly once");
    expect(message).toContain("--accept-existing");
    expect(message).toMatch(/Do NOT reach for --force/);
    // and it names the source to diff against, not just the destination
    expect(message).toContain("docs/worker-pm-workflow.md");
  });

  it("--accept-existing adopts an unrecorded destination, and records it thereafter", () => {
    seedSources(fakeRepoRoot);
    const targetDir = join(workDir, "target");
    const config = cfg(targetDir);
    const receiptPath = join(workDir, "distribute.receipt.json");
    mkdirSync(targetDir, { recursive: true });
    writeFileSync(config.targets[0].workerDocDest, "SOMETHING NOBODY RECORDED");

    distribute({
      config,
      repoRoot: fakeRepoRoot,
      build: false,
      receiptPath,
      acceptExisting: true,
    });
    expect(readFileSync(config.targets[0].workerDocDest, "utf8")).toContain("WORKER_WORKFLOW");

    // Adopted once; from here the ordinary guard applies without the flag.
    writeFileSync(config.targets[0].workerDocDest, "edited again");
    expect(() => distribute({ config, repoRoot: fakeRepoRoot, build: false, receiptPath })).toThrow(
      /changed since distribute last wrote it/,
    );
  });

  it("no receiptPath keeps the previous behaviour exactly -- no file, no guard", () => {
    seedSources(fakeRepoRoot);
    const config = cfg(join(workDir, "target"));

    distribute({ config, repoRoot: fakeRepoRoot, build: false });
    writeFileSync(config.targets[0].workerDocDest, "edited");
    expect(() => distribute({ config, repoRoot: fakeRepoRoot, build: false })).not.toThrow();
    expect(existsSync(join(workDir, "distribute.receipt.json"))).toBe(false);
  });

  it("a dry run neither writes artifacts nor a receipt", () => {
    seedSources(fakeRepoRoot);
    const config = cfg(join(workDir, "target"));
    const receiptPath = join(workDir, "distribute.receipt.json");

    distribute({ config, repoRoot: fakeRepoRoot, build: false, dryRun: true, receiptPath });

    expect(existsSync(receiptPath)).toBe(false);
    expect(existsSync(config.targets[0].workerDocDest)).toBe(false);
  });

  it("a corrupt receipt throws rather than degrading to 'no record'", () => {
    const receiptPath = join(workDir, "distribute.receipt.json");
    writeFileSync(receiptPath, "{not json");
    // The permissive reading of a damaged receipt is exactly the state this
    // guard exists to prevent, so it must not be the fallback.
    expect(() => loadReceipt(receiptPath)).toThrow(/unreadable/);
  });

  it("receiptPathFor puts the receipt beside the config", () => {
    const p = receiptPathFor(join(workDir, "nested", "distribute.config.json"));
    expect(p).toBe(join(workDir, "nested", "distribute.receipt.json"));
  });
});

describe("applyBanner", () => {
  it("keeps the shebang first so a bundle stays executable", () => {
    const src = Buffer.from("#!/usr/bin/env node\nconsole.log(1);\n", "utf8");
    const out = applyBanner(src, "x/pm-integrator.mjs", "src/bundle.mjs").toString("utf8");
    const lines = out.split("\n");
    expect(lines[0]).toBe("#!/usr/bin/env node");
    expect(lines[1]).toMatch(/^\/\/ GENERATED by scripts\/distribute\.mjs from src\/bundle\.mjs/);
    expect(out).toContain("console.log(1);");
  });

  it("uses an HTML comment for markdown, so rendered docs are unchanged", () => {
    const out = applyBanner(Buffer.from("# Title\n", "utf8"), "x/doc.md", "docs/src.md").toString(
      "utf8",
    );
    expect(out.startsWith("<!-- GENERATED by scripts/distribute.mjs from docs/src.md")).toBe(true);
    expect(out).toContain("# Title");
  });

  it("leaves an unknown file type byte-identical rather than guessing a comment syntax", () => {
    const src = Buffer.from([0, 1, 2, 3]);
    expect(applyBanner(src, "x/thing.bin", "src/thing.bin").equals(src)).toBe(true);
  });
});
